'use client';

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Lang = 'id' | 'en';

interface LanguageContextValue {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
}

const dict: Record<Lang, Record<string, string>> = {
  id: {
    /* -- Navbar -- */
    'nav.home': 'Beranda',
    'nav.collection': 'Koleksi Mobil',
    'nav.about': 'Tentang Kami',
    'nav.admin': 'Admin',
    'nav.menu': 'Menu',
    'nav.cars': 'Koleksi Lengkap',

    /* -- Hero -- */
    'hero.badge': 'Dealer Mobil Keluarga Terpercaya',
    'hero.title': 'Masa Depan Keluarga Anda Dimulai di Sini.',
    'hero.subtitle':
      'Kami menghadirkan koleksi mobil bekas premium berkualitas terbaik. Setiap unit melewati 65 titik inspeksi ketat untuk memastikan keamanan & kenyamanan keluarga Anda.',
    'hero.btn.collection': 'Lihat Koleksi',
    'hero.btn.consult': 'Konsultasi WA',

    /* -- Catalog -- */
    'catalog.title': 'Unit Keluarga Pilihan',
    'catalog.subtitle':
      'Temukan mobil yang sempurna untuk menemani setiap momen berharga keluarga Anda.',
    'catalog.search': 'Cari merek atau model...',
    'catalog.all': 'Semua',
    'catalog.showing': 'Menampilkan {shown} unit dari {total}',
    'catalog.empty': 'Belum ada mobil tersedia saat ini.',
    'catalog.empty.sub': 'Unit baru akan segera hadir.',
    'catalog.seeAll': 'Lihat Selengkapnya',
    'catalog.allShown': 'Semua {total} unit telah ditampilkan',
    'catalog.more': '{count} lagi',

    /* -- Car Card -- */
    'car.cashPrice': 'Harga Cash',
    'car.km': 'KM',
    'car.featured': 'Featured',
    'car.sold': 'Terjual',
    'car.available': 'Tersedia',
    'car.specs.km': 'Kilometer',
    'car.specs.transmission': 'Transmisi',
    'car.specs.fuel': 'Bahan Bakar',
    'car.specs.color': 'Warna',
    'car.description': 'Deskripsi',
    'car.back': 'Kembali ke Koleksi',
    'car.whatsapp': 'Tanya Via WhatsApp',

    'car.phone': 'Telepon Showroom',

    /* -- Cars Page -- */
    'cars.title': 'Koleksi Mobil',
    'cars.units': 'Unit Tersedia',
    'cars.subtitle': 'Temukan mobil impian keluarga Anda dari koleksi premium kami.',
    'cars.search': 'Cari merek atau model...',
    'cars.brand': 'Merek:',
    'cars.all': 'Semua',
    'cars.sort.newest': 'Terbaru',
    'cars.sort.priceAsc': 'Harga Terendah',
    'cars.sort.priceDesc': 'Harga Tertinggi',
    'cars.sort.yearDesc': 'Tahun Terbaru',
    'cars.sort.yearAsc': 'Tahun Terlama',
    'cars.found': 'unit ditemukan',
    'cars.empty': 'Tidak ada mobil ditemukan.',
    'cars.empty.sub': 'Coba ubah filter pencarian Anda.',
    'cars.detail': 'Detail',
    'cars.wa': 'WhatsApp',


    /* -- Features -- */
    'features.title': 'Standar Premium Kami',
    'features.1.title': 'Inspeksi Ketat',
    'features.1.desc':
      'Setiap unit melewati 65 titik pemeriksaan menyeluruh oleh teknisi ahli kami. Dari kondisi mesin, transmisi, hingga interior Â— tidak ada yang terlewat.',
    'features.2.title': 'Dokumen Terjamin',
    'features.2.desc':
      'BPKB, STNK, dan faktur asli lengkap. Kami urus proses balik nama hingga selesai. Bebas sengketa dan siap pakai untuk keluarga Anda.',
    'features.3.title': 'Harga Transparan',
    'features.3.desc':
      'Harga yang tercantum adalah harga final Â— tanpa biaya tersembunyi. Dapatkan penawaran terbaik dengan promo cicilan 0% melalui mitra pembiayaan kami.',

    /* -- Testimonials -- */
    'testimonials.title': 'Apa Kata Pelanggan Kami',

    /* -- Footer -- */
    'footer.desc':
      'Spesialis mobil keluarga bekas berkualitas premium. Kami menjamin setiap unit yang Anda bawa pulang adalah yang terbaik untuk keluarga Anda.',
    'footer.quickLinks': 'Tautan Cepat',
    'footer.collection': 'Koleksi Mobil',
    'footer.credit': 'Simulasi Kredit',
    'footer.consignment': 'Titip Jual',
    'footer.about': 'Tentang Kami',
    'footer.contact': 'Kontak Showroom',
    'footer.copyright': 'Hak Cipta Dilindungi. Bukan bagian dari Audi AG.',
    'footer.terms': 'Syarat & Ketentuan',
    'footer.privacy': 'Kebijakan Privasi',

    /* -- Stats -- */
    'stats.units': 'Unit Tersedia',
    'stats.brands': 'Merek Premium',
    'stats.inspection': 'Titik Inspeksi',
    'stats.legal': 'Dokumen Legal',

    /* -- Gallery -- */
    'gallery.title': 'Showroom Kami',

    /* -- Promotions -- */
    'promotions.title': 'Penawaran Spesial',

    /* -- Map / Contact -- */
    'map.title': 'Hubungi Kami',
    'map.location': 'Lokasi Showroom',
    'map.address': 'Alamat',
    'map.phone': 'Telepon',
    'map.email': 'Email',

    /* -- Login -- */
    'login.title': 'Admin Panel Login',
    'login.subtitle': 'Masuk ke Dashboard',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.usernamePlaceholder': 'Masukkan username',
    'login.passwordPlaceholder': 'Masukkan password',
    'login.error': 'Login gagal',
    'login.connectionError': 'Terjadi kesalahan koneksi',
    'login.button': 'Masuk',
    'login.buttonLoading': 'Masuk...',
    'login.back': 'Kembali ke Beranda',

    /* -- Dashboard -- */
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Kelola showroom Audi Motor',
    'dashboard.addCar': 'Tambah Mobil',
    'dashboard.loading': 'Memuat data...',
    'dashboard.totalCars': 'Total Mobil',
    'dashboard.available': 'Tersedia',
    'dashboard.sold': 'Terjual',
    'dashboard.totalValue': 'Total Nilai',
    'dashboard.unitsRegistered': 'unit terdaftar',
    'dashboard.readyToSell': 'siap dijual',
    'dashboard.unitsSold': 'unit terjual',
    'dashboard.inventoryValue': 'nilai inventory',
    'dashboard.inventory': 'Inventory Mobil',
    'dashboard.empty': 'Belum ada mobil. Tambahkan mobil pertama Anda!',
    'dashboard.table.car': 'Mobil',
    'dashboard.table.year': 'Tahun',
    'dashboard.table.price': 'Harga',
    'dashboard.table.km': 'KM',
    'dashboard.table.status': 'Status',
    'dashboard.table.action': 'Aksi',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Hapus',
    'dashboard.deleteConfirm': 'Yakin ingin menghapus mobil ini?',

    /* -- Car Form -- */
    'carForm.addTitle': 'Tambah Mobil Baru',
    'carForm.editTitle': 'Edit Mobil',
    'carForm.brand': 'Merek *',
    'carForm.model': 'Nama Model *',
    'carForm.variant': 'Varian',
    'carForm.year': 'Tahun *',
    'carForm.price': 'Harga (Rp) *',
    'carForm.kilometer': 'Kilometer *',
    'carForm.transmission': 'Transmisi',
    'carForm.fuel': 'Bahan Bakar',
    'carForm.color': 'Warna',
    'carForm.status': 'Status',
    'carForm.transmissionAuto': 'Automatic',
    'carForm.transmissionManual': 'Manual',
    'carForm.transmissionCVT': 'CVT',
    'carForm.transmissionDCT': 'DCT',
    'carForm.fuelGas': 'Bensin',
    'carForm.fuelDiesel': 'Diesel',
    'carForm.fuelHybrid': 'Hybrid',
    'carForm.fuelElectric': 'Listrik',
    'carForm.statusAvailable': 'Tersedia',
    'carForm.statusSold': 'Terjual',
    'carForm.statusFeatured': 'Featured',
    'carForm.image': 'Gambar Mobil',
    'carForm.upload': 'Upload Gambar',
    'carForm.uploadOr': 'atau paste URL di bawah',
    'carForm.description': 'Deskripsi',
    'carForm.featured': 'Tandai sebagai Featured',
    'carForm.save': 'Simpan Mobil',
    'carForm.saveChanges': 'Simpan Perubahan',
    'carForm.cancel': 'Batal',
    'carForm.back': 'Kembali ke Dashboard',

    /* -- Admin sidebar -- */
    'admin.dashboard': 'Dashboard',
    'admin.cmsSettings': 'CMS Settings',
    'admin.hero': 'Hero Section',
    'admin.features': 'Fitur',
    'admin.gallery': 'Gallery',
    'admin.testimonials': 'Testimoni',
    'admin.promotions': 'Promosi',
    'admin.pages': 'Halaman',
    'admin.contact': 'Kontak',
    'admin.social': 'Social Media',
    'admin.addCar': 'Tambah Mobil',
    'admin.settings': 'Pengaturan',
    'admin.mainMenu': 'Menu Utama',
    'admin.viewSite': 'Lihat Website',
    'admin.logout': 'Logout',
    'admin.you': '(Anda)',
    'admin.noName': 'Tanpa nama',

    /* -- Settings -- */
    'settings.profile': 'Profil Saya',
    'settings.userManagement': 'Manajemen User',
    'settings.roleConfig': 'Konfigurasi Role',
    'settings.accountInfo': 'Informasi Akun',
    'settings.profileInfo': 'Profil',
    'settings.changePassword': 'Ubah Password',
    'settings.fullName': 'Nama Lengkap',
    'settings.oldPassword': 'Password Lama',
    'settings.newPassword': 'Password Baru',
    'settings.confirmPassword': 'Konfirmasi Password Baru',
    'settings.passwordHint': 'Kosongkan jika tidak ingin mengubah password',
    'settings.save': 'Simpan Perubahan',
    'settings.addUser': 'Tambah User Baru',
    'settings.editUser': 'Edit User',
    'settings.addRole': 'Tambah Role Baru',
    'settings.editRole': 'Edit Role',
    'settings.permissions': 'Hak Akses per Menu CMS',
    'settings.permissionNone': 'Tidak Ada',
    'settings.permissionView': 'Lihat Saja',
    'settings.permissionEdit': 'Lihat & Edit',
    'settings.active': 'Aktif',
    'settings.inactive': 'Nonaktif',
    'settings.deactivate': 'Nonaktifkan',
    'settings.activate': 'Aktifkan',
    'settings.delete': 'Hapus',
    'settings.deleteUserConfirm': 'Yakin ingin menghapus user ini?',

    /* -- CMS -- */
    'cms.general': 'Umum',
    'cms.contact': 'Kontak',
    'cms.social': 'Social Media',
    'cms.seo': 'SEO',
    'cms.siteName': 'Nama Website',
    'cms.tagline': 'Tagline',
    'cms.description': 'Deskripsi Website',
    'cms.logo': 'Logo Website',
    'cms.favicon': 'Favicon',
    'cms.save': 'Simpan Pengaturan',
    'cms.hero': 'Hero Section',
    'cms.heroDesc': 'Kelola konten hero section di halaman utama',
    'cms.bgImage': 'Background Image',
    'cms.bgVideo': 'Background Video',
    'cms.heroContent': 'Konten Hero',
    'cms.badge': 'Badge Teks',
    'cms.mainTitle': 'Judul Utama',
    'cms.subtitle': 'Subtitle',
    'cms.cta': 'Tombol Aksi',
    'cms.ctaText': 'Teks Tombol Utama',
    'cms.ctaLink': 'Link Tombol Utama',
    'cms.ctaSecondaryText': 'Teks Tombol Sekunder',
    'cms.ctaSecondaryLink': 'Link Tombol Sekunder',
    'cms.saveHero': 'Simpan Hero',
    'cms.features': 'Kelola Fitur',
    'cms.featuresDesc': 'Tambah, edit, atau hapus fitur yang ditampilkan di homepage',
    'cms.addFeature': 'Tambah Fitur Baru',
    'cms.editFeature': 'Edit Fitur',
    'cms.icon': 'Icon',
    'cms.title': 'Judul',
    'cms.desc': 'Deskripsi',
    'cms.order': 'Urutan',
    'cms.active': 'Aktif',
    'cms.emptyFeatures': 'Belum ada fitur. Tambahkan fitur pertama Anda!',
    'cms.gallery': 'Gallery',
    'cms.galleryDesc': 'Kelola gambar showroom dan gallery website',
    'cms.addImage': 'Tambah Gambar Baru',
    'cms.editImage': 'Edit Gambar',
    'cms.category': 'Kategori',
    'cms.catShowroom': 'Showroom',
    'cms.catCar': 'Mobil',
    'cms.catInterior': 'Interior',
    'cms.catExterior': 'Eksterior',
    'cms.catPromo': 'Promo',
    'cms.catGeneral': 'Umum',
    'cms.testimonials': 'Testimoni Pelanggan',
    'cms.testimonialsDesc': 'Kelola testimoni dari pelanggan yang puas',
    'cms.addTestimonial': 'Tambah Testimonial Baru',
    'cms.editTestimonial': 'Edit Testimonial',
    'cms.customerName': 'Nama Pelanggan',
    'cms.carPurchased': 'Mobil yang Dibeli',
    'cms.rating': 'Rating (1-5)',
    'cms.testimonial': 'Testimonial',
    'cms.promotions': 'Promosi',
    'cms.promotionsDesc': 'Kelola promosi dan penawaran spesial',
    'cms.addPromotion': 'Tambah Promosi Baru',
    'cms.editPromotion': 'Edit Promosi',
    'cms.promoTitle': 'Judul Promosi',
    'cms.discountText': 'Teks Diskon',
    'cms.promoDesc': 'Deskripsi',
    'cms.startDate': 'Tanggal Mulai',
    'cms.endDate': 'Tanggal Berakhir',
    'cms.promoImage': 'Gambar Promosi',
    'cms.contact': 'Kontak',
    'cms.contactDesc': 'Kelola informasi kontak showroom',
    'cms.addContact': 'Tambah Kontak Baru',
    'cms.editContact': 'Edit Kontak',
    'cms.contactType': 'Jenis Kontak',
    'cms.label': 'Label',
    'cms.value': 'Nilai Kontak',
    'cms.typeAddress': 'Alamat',
    'cms.typePhone': 'Telepon',
    'cms.typeWhatsApp': 'WhatsApp',
    'cms.typeEmail': 'Email',
    'cms.typeFax': 'Fax',
    'cms.typeOther': 'Lainnya',
    'cms.social': 'Social Media',
    'cms.socialDesc': 'Kelola link media sosial showroom',
    'cms.addSocial': 'Tambah Social Link Baru',
    'cms.editSocial': 'Edit Social Link',
    'cms.platform': 'Platform',
    'cms.url': 'URL',
    'cms.pages': 'Halaman',
    'cms.pagesDesc': 'Kelola halaman konten website (Syarat & Ketentuan, Kebijakan Privasi, dll)',
    'cms.addPage': 'Tambah Halaman Baru',
    'cms.editPage': 'Edit Halaman',
    'cms.slug': 'Slug (URL)',
    'cms.pageTitle': 'Judul',
    'cms.content': 'Konten (HTML)',
    'cms.metaDesc': 'Meta Description (SEO)',

    /* -- Permissions -- */
    'perm.redirecting': 'Mengalihkan ke login...',
    'perm.loading': 'Memuat...',
    'perm.denied': 'Akses Ditolak',
    'perm.noAccess': 'Anda tidak memiliki izin untuk mengakses halaman ini.',

    /* -- Cars Page -- */
    'cars.title': 'Koleksi Lengkap',
    'cars.subtitle': 'Temukan mobil impian keluarga Anda dari koleksi premium kami',
    'cars.units': 'Unit Tersedia',
    'cars.search': 'Cari merek, model...',
    'cars.brand': 'Merek:',
    'cars.all': 'Semua',
    'cars.found': 'unit ditemukan',
    'cars.empty': 'Tidak ada mobil ditemukan',
    'cars.empty.sub': 'Coba ubah filter atau kata kunci pencarian',
    'cars.sort.newest': 'Terbaru',
    'cars.sort.priceAsc': 'Harga Terendah',
    'cars.sort.priceDesc': 'Harga Tertinggi',
    'cars.sort.yearDesc': 'Tahun Terbaru',
    'cars.sort.yearAsc': 'Tahun Terlama',
    'cars.detail': 'Detail',
    'cars.wa': 'WA',
  },
  en: {
    /* -- Navbar -- */
    'nav.home': 'Home',
    'nav.collection': 'Car Collection',
    'nav.about': 'About Us',
    'nav.admin': 'Admin',
    'nav.menu': 'Menu',
    'nav.cars': 'Full Collection',

    /* -- Hero -- */
    'hero.badge': 'Trusted Family Car Dealer',
    'hero.title': 'Your Family\'s Future Starts Here.',
    'hero.subtitle':
      'We present a collection of premium quality used cars. Each unit passes 65 strict inspection points to ensure the safety & comfort of your family.',
    'hero.btn.collection': 'View Collection',
    'hero.btn.consult': 'WhatsApp Consult',

    /* -- Catalog -- */
    'catalog.title': 'Premium Family Units',
    'catalog.subtitle':
      'Find the perfect car to accompany every precious moment of your family.',
    'catalog.search': 'Search brand or model...',
    'catalog.all': 'All',
    'catalog.showing': 'Showing {shown} of {total} units',
    'catalog.empty': 'No cars available at the moment.',
    'catalog.empty.sub': 'New units coming soon.',
    'catalog.seeAll': 'See All Collection',
    'catalog.allShown': 'All {total} units have been displayed',
    'catalog.more': '{count} more',

    /* -- Car Card -- */
    'car.cashPrice': 'Cash Price',
    'car.km': 'KM',
    'car.featured': 'Featured',
    'car.sold': 'Sold',
    'car.available': 'Available',
    'car.specs.km': 'Kilometers',
    'car.specs.transmission': 'Transmission',
    'car.specs.fuel': 'Fuel',
    'car.specs.color': 'Color',
    'car.description': 'Description',
    'car.back': 'Back to Collection',
    'car.whatsapp': 'Ask via WhatsApp',
        'car.whatsapp': 'Ask via WhatsApp',
    'car.phone': 'Call Showroom',

    /* -- Cars Page -- */
    'cars.title': 'Car Collection',
    'cars.units': 'Available Units',
    'cars.subtitle': 'Find your family\'s dream car from our premium collection.',
    'cars.search': 'Search brand or model...',
    'cars.brand': 'Brand:',
    'cars.all': 'All',
    'cars.sort.newest': 'Newest',
    'cars.sort.priceAsc': 'Lowest Price',
    'cars.sort.priceDesc': 'Highest Price',
    'cars.sort.yearDesc': 'Newest Year',
    'cars.sort.yearAsc': 'Oldest Year',
    'cars.found': 'units found',
    'cars.empty': 'No cars found.',
    'cars.empty.sub': 'Try changing your search filters.',
    'cars.detail': 'Details',
    'cars.wa': 'WhatsApp',


    /* -- Features -- */
    'features.title': 'Our Premium Standards',
    'features.1.title': 'Strict Inspection',
    'features.1.desc':
      'Each unit undergoes 65 comprehensive checkpoints by our expert technicians. From engine condition, transmission, to interior Â— nothing is missed.',
    'features.2.title': 'Guaranteed Documents',
    'features.2.desc':
      'Complete original BPKB, STNK, and invoices. We handle the name transfer process until completion. Dispute-free and ready for your family.',
    'features.3.title': 'Transparent Pricing',
    'features.3.desc':
      'The listed price is the final price Â— no hidden fees. Get the best deals with 0% installment promos through our financing partners.',

    /* -- Testimonials -- */
    'testimonials.title': 'What Our Customers Say',

    /* -- Footer -- */
    'footer.desc':
      'Premium used family car specialist. We guarantee every unit you take home is the best for your family.',
    'footer.quickLinks': 'Quick Links',
    'footer.collection': 'Car Collection',
    'footer.credit': 'Credit Simulation',
    'footer.consignment': 'Consignment',
    'footer.about': 'About Us',
    'footer.contact': 'Showroom Contact',
    'footer.copyright': 'All Rights Reserved. Not affiliated with Audi AG.',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',

    /* -- Stats -- */
    'stats.units': 'Available Units',
    'stats.brands': 'Premium Brands',
    'stats.inspection': 'Inspection Points',
    'stats.legal': 'Legal Documents',

    /* -- Gallery -- */
    'gallery.title': 'Our Showroom',

    /* -- Promotions -- */
    'promotions.title': 'Special Offers',

    /* -- Map / Contact -- */
    'map.title': 'Contact Us',
    'map.location': 'Showroom Location',
    'map.address': 'Address',
    'map.phone': 'Phone',
    'map.email': 'Email',

    /* -- Login -- */
    'login.title': 'Admin Panel Login',
    'login.subtitle': 'Sign in to Dashboard',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.usernamePlaceholder': 'Enter username',
    'login.passwordPlaceholder': 'Enter password',
    'login.error': 'Login failed',
    'login.connectionError': 'Connection error occurred',
    'login.button': 'Sign In',
    'login.buttonLoading': 'Signing in...',
    'login.back': 'Back to Home',

    /* -- Dashboard -- */
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Manage Audi Motor showroom',
    'dashboard.addCar': 'Add Car',
    'dashboard.loading': 'Loading data...',
    'dashboard.totalCars': 'Total Cars',
    'dashboard.available': 'Available',
    'dashboard.sold': 'Sold',
    'dashboard.totalValue': 'Total Value',
    'dashboard.unitsRegistered': 'units registered',
    'dashboard.readyToSell': 'ready to sell',
    'dashboard.unitsSold': 'units sold',
    'dashboard.inventoryValue': 'inventory value',
    'dashboard.inventory': 'Car Inventory',
    'dashboard.empty': 'No cars yet. Add your first car!',
    'dashboard.table.car': 'Car',
    'dashboard.table.year': 'Year',
    'dashboard.table.price': 'Price',
    'dashboard.table.km': 'KM',
    'dashboard.table.status': 'Status',
    'dashboard.table.action': 'Action',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Delete',
    'dashboard.deleteConfirm': 'Are you sure you want to delete this car?',

    /* -- Car Form -- */
    'carForm.addTitle': 'Add New Car',
    'carForm.editTitle': 'Edit Car',
    'carForm.brand': 'Brand *',
    'carForm.model': 'Model Name *',
    'carForm.variant': 'Variant',
    'carForm.year': 'Year *',
    'carForm.price': 'Price (Rp) *',
    'carForm.kilometer': 'Kilometers *',
    'carForm.transmission': 'Transmission',
    'carForm.fuel': 'Fuel',
    'carForm.color': 'Color',
    'carForm.status': 'Status',
    'carForm.transmissionAuto': 'Automatic',
    'carForm.transmissionManual': 'Manual',
    'carForm.transmissionCVT': 'CVT',
    'carForm.transmissionDCT': 'DCT',
    'carForm.fuelGas': 'Gasoline',
    'carForm.fuelDiesel': 'Diesel',
    'carForm.fuelHybrid': 'Hybrid',
    'carForm.fuelElectric': 'Electric',
    'carForm.statusAvailable': 'Available',
    'carForm.statusSold': 'Sold',
    'carForm.statusFeatured': 'Featured',
    'carForm.image': 'Car Image',
    'carForm.upload': 'Upload Image',
    'carForm.uploadOr': 'or paste URL below',
    'carForm.description': 'Description',
    'carForm.featured': 'Mark as Featured',
    'carForm.save': 'Save Car',
    'carForm.saveChanges': 'Save Changes',
    'carForm.cancel': 'Cancel',
    'carForm.back': 'Back to Dashboard',

    /* -- Admin sidebar -- */
    'admin.dashboard': 'Dashboard',
    'admin.cmsSettings': 'CMS Settings',
    'admin.hero': 'Hero Section',
    'admin.features': 'Features',
    'admin.gallery': 'Gallery',
    'admin.testimonials': 'Testimonials',
    'admin.promotions': 'Promotions',
    'admin.pages': 'Pages',
    'admin.contact': 'Contact',
    'admin.social': 'Social Media',
    'admin.addCar': 'Add Car',
    'admin.settings': 'Settings',
    'admin.mainMenu': 'Main Menu',
    'admin.viewSite': 'View Site',
    'admin.logout': 'Logout',
    'admin.you': '(You)',
    'admin.noName': 'No name',

    /* -- Settings -- */
    'settings.profile': 'My Profile',
    'settings.userManagement': 'User Management',
    'settings.roleConfig': 'Role Configuration',
    'settings.accountInfo': 'Account Information',
    'settings.profileInfo': 'Profile',
    'settings.changePassword': 'Change Password',
    'settings.fullName': 'Full Name',
    'settings.oldPassword': 'Old Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.passwordHint': 'Leave blank if you don\'t want to change password',
    'settings.save': 'Save Changes',
    'settings.addUser': 'Add New User',
    'settings.editUser': 'Edit User',
    'settings.addRole': 'Add New Role',
    'settings.editRole': 'Edit Role',
    'settings.permissions': 'CMS Menu Access Rights',
    'settings.permissionNone': 'None',
    'settings.permissionView': 'View Only',
    'settings.permissionEdit': 'View & Edit',
    'settings.active': 'Active',
    'settings.inactive': 'Inactive',
    'settings.deactivate': 'Deactivate',
    'settings.activate': 'Activate',
    'settings.delete': 'Delete',
    'settings.deleteUserConfirm': 'Are you sure you want to delete this user?',

    /* -- CMS -- */
    'cms.general': 'General',
    'cms.contact': 'Contact',
    'cms.social': 'Social Media',
    'cms.seo': 'SEO',
    'cms.siteName': 'Site Name',
    'cms.tagline': 'Tagline',
    'cms.description': 'Site Description',
    'cms.logo': 'Site Logo',
    'cms.favicon': 'Favicon',
    'cms.save': 'Save Settings',
    'cms.hero': 'Hero Section',
    'cms.heroDesc': 'Manage hero section content on the homepage',
    'cms.bgImage': 'Background Image',
    'cms.bgVideo': 'Background Video',
    'cms.heroContent': 'Hero Content',
    'cms.badge': 'Badge Text',
    'cms.mainTitle': 'Main Title',
    'cms.subtitle': 'Subtitle',
    'cms.cta': 'Call to Action',
    'cms.ctaText': 'Primary Button Text',
    'cms.ctaLink': 'Primary Button Link',
    'cms.ctaSecondaryText': 'Secondary Button Text',
    'cms.ctaSecondaryLink': 'Secondary Button Link',
    'cms.saveHero': 'Save Hero',
    'cms.features': 'Manage Features',
    'cms.featuresDesc': 'Add, edit, or delete features displayed on the homepage',
    'cms.addFeature': 'Add New Feature',
    'cms.editFeature': 'Edit Feature',
    'cms.icon': 'Icon',
    'cms.title': 'Title',
    'cms.desc': 'Description',
    'cms.order': 'Order',
    'cms.active': 'Active',
    'cms.emptyFeatures': 'No features yet. Add your first feature!',
    'cms.gallery': 'Gallery',
    'cms.galleryDesc': 'Manage showroom images and website gallery',
    'cms.addImage': 'Add New Image',
    'cms.editImage': 'Edit Image',
    'cms.category': 'Category',
    'cms.catShowroom': 'Showroom',
    'cms.catCar': 'Car',
    'cms.catInterior': 'Interior',
    'cms.catExterior': 'Exterior',
    'cms.catPromo': 'Promo',
    'cms.catGeneral': 'General',
    'cms.testimonials': 'Customer Testimonials',
    'cms.testimonialsDesc': 'Manage testimonials from satisfied customers',
    'cms.addTestimonial': 'Add New Testimonial',
    'cms.editTestimonial': 'Edit Testimonial',
    'cms.customerName': 'Customer Name',
    'cms.carPurchased': 'Car Purchased',
    'cms.rating': 'Rating (1-5)',
    'cms.testimonial': 'Testimonial',
    'cms.promotions': 'Promotions',
    'cms.promotionsDesc': 'Manage promotions and special offers',
    'cms.addPromotion': 'Add New Promotion',
    'cms.editPromotion': 'Edit Promotion',
    'cms.promoTitle': 'Promotion Title',
    'cms.discountText': 'Discount Text',
    'cms.promoDesc': 'Description',
    'cms.startDate': 'Start Date',
    'cms.endDate': 'End Date',
    'cms.promoImage': 'Promotion Image',
    'cms.contact': 'Contact',
    'cms.contactDesc': 'Manage showroom contact information',
    'cms.addContact': 'Add New Contact',
    'cms.editContact': 'Edit Contact',
    'cms.contactType': 'Contact Type',
    'cms.label': 'Label',
    'cms.value': 'Contact Value',
    'cms.typeAddress': 'Address',
    'cms.typePhone': 'Phone',
    'cms.typeWhatsApp': 'WhatsApp',
    'cms.typeEmail': 'Email',
    'cms.typeFax': 'Fax',
    'cms.typeOther': 'Other',
    'cms.social': 'Social Media',
    'cms.socialDesc': 'Manage showroom social media links',
    'cms.addSocial': 'Add New Social Link',
    'cms.editSocial': 'Edit Social Link',
    'cms.platform': 'Platform',
    'cms.url': 'URL',
    'cms.pages': 'Pages',
    'cms.pagesDesc': 'Manage website content pages (Terms & Conditions, Privacy Policy, etc.)',
    'cms.addPage': 'Add New Page',
    'cms.editPage': 'Edit Page',
    'cms.slug': 'Slug (URL)',
    'cms.pageTitle': 'Title',
    'cms.content': 'Content (HTML)',
    'cms.metaDesc': 'Meta Description (SEO)',

    /* -- Permissions -- */
    'perm.redirecting': 'Redirecting to login...',
    'perm.loading': 'Loading...',
    'perm.denied': 'Access Denied',
    'perm.noAccess': 'You do not have permission to access this page.',

    /* -- Cars Page -- */
    'cars.title': 'Full Collection',
    'cars.subtitle': 'Find your dream family car from our premium collection',
    'cars.units': 'Available Units',
    'cars.search': 'Search brand, model...',
    'cars.brand': 'Brand:',
    'cars.all': 'All',
    'cars.found': 'units found',
    'cars.empty': 'No cars found',
    'cars.empty.sub': 'Try changing filters or search keywords',
    'cars.sort.newest': 'Newest',
    'cars.sort.priceAsc': 'Lowest Price',
    'cars.sort.priceDesc': 'Highest Price',
    'cars.sort.yearDesc': 'Newest Year',
    'cars.sort.yearAsc': 'Oldest Year',
    'cars.detail': 'Detail',
    'cars.wa': 'WA',
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'id',
  toggleLang: () => {},
  t: (k: string) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('id');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang | null;
    if (saved) setLangState(saved);
    setMounted(true);
  }, []);

  const toggleLang = () => {
    const next = lang === 'id' ? 'en' : 'id';
    setLangState(next);
    localStorage.setItem('lang', next);
  };

  const t = (key: string): string => {
    const val = dict[lang][key];
    return val ?? key;
  };

  if (!mounted) {
    /* render children immediately so they can read lang synchronously on first paint */
  }

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);


